export const usersSeed = [
  { 
    autoGenerated: true,
    sensi: true, 
    author: true, 
    phash: '$2b$10$XNRaUv/zojakZ/18qiP4M.QJYJmGkAn5725wlIlI68Uy2b4Ex/8O6', 
    userName: "bart", 
    status: "active", 
    userEmail: "b0rgbart3@gmail.com" },
  { 
    autoGenerated: true,
    sensi: false, 
    author: true, 
    phash: '$2b$10$SFWaw/YCRtZ2Ru/1VEjNQOt.3iw4un0JGmau8irpn0aclI1dPD7Hq', 
    userName: "dumbo", 
    status: "active", 
    userEmail: "dumbo@somewhere.org" }
];
