import mongoose from "mongoose";

const UsersSchema = new mongoose.Schema({
  autoGenerated: Boolean,
  sensi: Boolean,
  author: Boolean,
  phash: String,
  status: String,
  userName: String,
  userEmail: String
});

export const Users = mongoose.model("users", UsersSchema);

