import { NextRequest, NextResponse } from 'next/server';
import { connectDB } from '@/src/lib/mongodb';
import { Users } from '@/src/models/Users';
import jwt, { Secret, SignOptions } from 'jsonwebtoken';
import bcrypt from 'bcrypt';

export async function POST(request: NextRequest) {
  await connectDB();
  try {
    const { userName, loginWord } = await request.json();
    const all = await Users.find();
    const foundUser = all.find((user) => user.userName === userName);

    let match = false;
    if (foundUser?.phash) {
      match = await bcrypt.compare(loginWord, foundUser.phash);
    }

    if (!match) {
      return NextResponse.json({ error: 'Invalid username or password' }, { status: 401 });
    }

    const payload = {
      autoGenerated: foundUser?.autoGenerated,
      _id: foundUser?._id,
      userName: foundUser?.userName,
      userEmail: foundUser?.userEmail,
      author: foundUser?.author,
      status: foundUser?.status,
      sensi: foundUser?.sensi,
    };

    const secret: Secret = process.env.JWT_SECRET as string;
    const expiresIn = (process.env.JWT_EXPIRES_IN as SignOptions['expiresIn']) || '2h';
    const token = jwt.sign(payload, secret, { expiresIn });

    return NextResponse.json({ token });
  } catch (err: any) {
    return NextResponse.json({ error: 'Error retrieving user info from the DB.' }, { status: 401 });
  }
}
